### ISSUE TITLE
[Bug] Request report is broken

### ISSUE THREAD

**Issue by roma-glushko** [roma-glushko/tango#28]
### Preconditions
Log File - transfer-ssl-2019-11-21.log

### Steps to reproduce
Run Report report:

```
tango request -l transfer-ssl-2019-11-21.log -r 11-21.request.csv
```

### Expected result
Request Report is generated successfully. 

### Actual results
Error is thrown, no report is generated:

```
💃 Tango is on the scene!
💃 started to generate a request report...
💃 reading access logs...
 71.73 MiB / 71.91 MiB [===============================================================]  99.74% 17s
💃 saving the request report...
panic: parse %.: invalid URL escape "%."

goroutine 1 [running]:
tango/internal/usecase/report.(*RequestReportUsecase).GenerateReport(0xc0001437d0, 0x7ffeefbff600, 0x11, 0xc00b42c000, 0x233a9, 0x2771c)
	/Users/glushko/Documents/Projects/etc/tango/internal/usecase/report/request-report-usecase.go:65 +0x655
tango/internal/cli/command.RequestReportCommand(0xc0000d0b00, 0x0, 0xc0000e2b60)
	/Users/glushko/Documents/Projects/etc/tango/internal/cli/command/request-report-command.go:26 +0x3c0
github.com/urfave/cli.HandleAction(0x14469e0, 0x151dc80, 0xc0000d0b00, 0xc0000d0b00, 0x0)
	/Users/glushko/go/pkg/mod/github.com/urfave/cli@v1.21.0/app.go:514 +0xbe
github.com/urfave/cli.Command.Run(0x14e7643, 0x7, 0x0, 0x0, 0xc0000ada60, 0x1, 0x1, 0x14f7118, 0x28, 0x0, ...)
	/Users/glushko/go/pkg/mod/github.com/urfave/cli@v1.21.0/command.go:171 +0x4cd
github.com/urfave/cli.(*App).Run(0xc00011a1c0, 0xc0000b8120, 0x6, 0x6, 0x0, 0x0)
	/Users/glushko/go/pkg/mod/github.com/urfave/cli@v1.21.0/app.go:265 +0x72f
tango/internal/cli.(*TangoCli).Run(0xc000143f48, 0xc0000b8120, 0x6, 0x6)
	/Users/glushko/Documents/Projects/etc/tango/internal/cli/tango-cli.go:208 +0x50
main.main()
	/Users/glushko/Documents/Projects/etc/tango/main.go:11 +0x5d
```

**Comment by roma-glushko** [comment]
During security scans, attackers can submit requests which are not looking like a regular URI. This triggered an issue during URI parsing via url.Parse().

Fix will be delivered in #36
